/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.wordpress.oreboladodeturing.wsdl.biblioteca_v1;

import java.util.logging.Logger;

import javax.annotation.Generated;

import com.wordpress.oreboladodeturing.model.webservices.BibliotecaService;

/**
 * This class was generated by Apache CXF 2.5.2 2012-03-18T16:53:56.696-03:00
 * Generated source version: 2.5.2
 * 
 */

@javax.jws.WebService(serviceName = "Biblioteca_v1_0", portName = "SOAPOverHTTP", targetNamespace = "http://oreboladodeturing.wordpress.com/wsdl/Biblioteca-v1/", wsdlLocation = "file:/host/works/Desenvolvimento/Java/workspace/cxf-jaxws-webservice-example/src/main/resources/wsdl/Biblioteca-v1.wsdl", endpointInterface = "com.wordpress.oreboladodeturing.wsdl.biblioteca_v1.BibliotecaV10")
@Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2012-03-18T16:53:56.696-03:00", comments = "Apache CXF 2.5.2")
public class BibliotecaV10Impl implements BibliotecaV10 {

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2012-03-18T16:53:56.696-03:00")
    private static final Logger LOG = Logger.getLogger(BibliotecaV10Impl.class.getName());
    private final BibliotecaService bibliotecaService;

    public BibliotecaV10Impl(final BibliotecaService bibliotecaService) {
	this.bibliotecaService = bibliotecaService;
    }

    /*
     * (non-Javadoc)
     * 
     * @see com.wordpress.oreboladodeturing.wsdl.biblioteca_v1.BibliotecaV10#
     * adicionarLivro
     * (com.wordpress.oreboladodeturing.xsd._2012._03.biblioteca.Livro
     * adicionarLivro )*
     */
    @Override
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2012-03-18T16:53:56.696-03:00")
    public java.lang.String adicionarLivro(final com.wordpress.oreboladodeturing.xsd._2012._03.biblioteca.Livro adicionarLivro) {
	LOG.info("Executing operation adicionarLivro");
	System.out.println(adicionarLivro);
	try {
	    final java.lang.String _return = bibliotecaService.adicionarLivro(adicionarLivro);
	    return _return;
	} catch (final java.lang.Exception ex) {
	    ex.printStackTrace();
	    throw new RuntimeException(ex);
	}
    }

}
